version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "jakarta.activation:jakarta.activation-api"
        versions: ">= 1.2.2"
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
        versions: ">= 3.0"
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: "> 3.1.0"
      # We are not ready for Jakarta EE 9 yet.
      - dependency-name: "org.glassfish.jersey:jersey-bom"
        versions: ">= 3.0"
  - package-ecosystem: "maven"
    directory: "/src/it/test1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/unconfigured"
    schedule:
      interval: "daily"
